### ISSUE TITLE
Right way to catch exceptions with :exoscale.ex/type key

### ISSUE THREAD

**Issue by velios** [exoscale/ex#30]
Let's say we want to handle errors that are guaranteed to be thrown by our application in some consistent way.
At the same time, in order to determine which errors are thrown by our application, and which by other libraries from the clojure ecosystem, we check for the presence of a type key.

```clojure
(try
     (throw (ex-info "Argh" {::ex/type ::bar :foo "a foo"}))
     (catch ExceptionInfo ex
       (if (some?  (::ex/type ex))
         (handle-special-way ex)
         (throw ex))
     (catch Exception ex
      (handle-other-ex)))
```

Does the library provide a better way to do this kind of checking?

**Comment by mpenet** [comment]
Hi, yes, check this lib provides a try+ macro that does exactly that. It’s described in the readme https://github.com/exoscale/ex?tab=readme-ov-file#the-basics

It behaves exactly like the default clojure try/catch/finally and adds a syntax for matching on ex data type.

**Comment by velios** [comment]
It seems to me that my question was not understood correctly. I wanted to know the correct way to not match to a specific type, like ::bar, but all errors which contain ::ex/type. Is there any syntactic sugar for this? I ask because separating ExceptionInfo is not enough, because it could be an error from a library in the clojure ecosystem.

**Comment by mpenet** [comment]
Got it. `try+` (and more generally ex), understands keyword hierarchies, so I guess you could create a keyword that is a parent of all known ex/type and match on this one. Just be aware that the hierarchy ex uses is part of the library, you can use exoscale.ex/derive to achieve this. It's described on the readme.
